"""
Run this script to generate an arduino sketch with a given
schema. We can't have arduino-time changeable schemas due to
the extremely small sketch and memory limits.
"""

import os
import subprocess
from typing import Dict


def generate_arduino_sketch(sketch_name: str,
                            schema: Dict[str, str],
                            pins: Dict[str, str] = None
                            ) -> None:
    """
    Make an arduino sketch in the current directory with the
    given chorded keyboard schema
    """
    fingers = [
        'pinky', 'ring', 'middle', 'pointer', 'thumb'
    ]

    required_pins = [
        f'{finger}_{state}_pin'
        for finger in fingers
        for state in ['up', 'down']
    ]
    for pin in required_pins:
        assert pin in pins, f'Missing {pin}'

    # Create folder
    os.mkdir(sketch_name)

    # Create file
    fp = f'{sketch_name}/{sketch_name}.ino'
    with open(fp, 'w') as f:
        # Header stuff
        f.write(
            '// This file was generated by a python script\n'
            '#include <Keyboard.h>\n'
            'enum FingerState { UP, OFF, DOWN };\n'
            'struct Chord { FingerState pinky = OFF, '
            'ring = OFF, middle = OFF, pointer = OFF, '
            'thumb = OFF; };\n'
        )

        # Pin information
        for pin in required_pins:
            p = pins[pin]
            f.write(f'const static int {pin} = {p};\n')

        # Setup
        f.write('void setup() {\n')
        for pin in required_pins:
            f.write(f'pinMode({pin}, INPUT_PULLUP);\n')
        f.write('Keyboard.begin();\n}\n')

        # Loop
        f.write('void loop() {\nChord state;\n')
        for finger in fingers:
            f.write(
                f'if (digitalRead({finger}_up_pin) == HIGH) '
                '{ state.' + finger + ' = UP; } else if ('
                f'digitalRead({finger}_down_pin) == HIGH)'
                ' { state.' + finger + ' = DOWN; }\n'
            )
            if finger == 'thumb':
                f.write('else { return; }\n')

        # Schema
        for pinky in ['UP', 'OFF', 'DOWN']:
            f.write(f'if (state.pinky == {pinky}) ' + '{\n')
            for ring in ['UP', 'OFF', 'DOWN']:
                f.write(f'if (state.ring == {ring}) ' + '{\n')
                for middle in ['UP', 'OFF', 'DOWN']:
                    f.write(f'if (state.middle == {middle}) '
                            + '{\n')
                    for pointer in ['UP', 'OFF', 'DOWN']:
                        f.write(
                            f'if (state.pointer == {pointer}) '
                            + '{\n'
                        )
                        for thumb in ['UP', 'DOWN']:
                            f.write(
                                f'if (state.thumb == {thumb}) '
                                + '{\n'
                            )

                            chord = ''.join(
                                [
                                    s[0] if s != 'OFF' else '0'
                                    for s in [
                                        pinky, ring, middle,
                                        pointer, thumb
                                    ]
                                ]
                            )

                            if chord in schema:
                                value = schema[chord]
                                if len(value) == 1:
                                    # Single char
                                    f.write(
                                        'Keyboard.press(\''
                                        + (
                                            f'\\{value}'
                                            if value in [
                                                '\'', '\\'
                                            ] else value
                                        ) + '\');\n'
                                    )

                                elif value.startswith('KEY_'):
                                    # Arduino keyboard constant
                                    f.write(
                                        'Keyboard.press('
                                        f'{value});\n'
                                    )

                                else:
                                    # Compound chord
                                    f.write(
                                        'Keyboard.print("'
                                        f'{value}");\n'
                                    )

                            else:
                                f.write(
                                    f'// {chord} is unused\n'
                                    'Keyboard.releaseAll();\n'
                                )

                            f.write('}\n')
                            if thumb != 'DOWN':
                                f.write(' else ')
                        f.write('}\n')
                        if pointer != 'DOWN':
                            f.write(' else ')
                    f.write('}\n')
                    if middle != 'DOWN':
                        f.write(' else ')
                f.write('}\n')
                if ring != 'DOWN':
                    f.write(' else ')
            f.write('}\n')
            if pinky != 'DOWN':
                f.write(' else ')

        f.write('}\n')

    # Attempt to format file
    subprocess.run(['clang-format', fp, '-i'], check=False)


if __name__ == '__main__':
    default_schema = {
        '0000U': 'KEY_TAB',
        '000UU': '8',
        '000DU': 'KEY_RIGHT_ARROW',
        '00U0U': '4',
        '00D0U': 'KEY_UP_ARROW',
        '0U00U': '2',
        '0UU0U': '6',
        '0D00U': 'KEY_DOWN_ARROW',
        '0DD0U': 'KEY_HOME',
        'U000U': '1',
        'U00UU': '9',
        'U0U0U': '5',
        'UU00U': '3',
        'UUU0U': '7',
        'UUUUU': 'KEY_ESC',
        'D000U': 'KEY_LEFT_ARROW',
        'DDDDU': 'KEY_CAPS_LOCK',
        '0000D': ' ',
        '000UD': 'r',
        '000DD': 'f',
        '00U0D': 'e',
        '00UUD': 'KEY_RETURN',
        '00UDD': 'v',
        '00D0D': 'd',
        '00DUD': 't',
        '00DDD': 'g',
        '0U00D': 'w',
        '0UU0D': 'KEY_BACKSPACE',
        '0UUUD': '0',
        '0UD0D': 'c',
        '0D00D': 's',
        'U000D': 'q',
        'U00DD': 'p',
        'UD00D': 'x',
        'DUDDD': 'z',
        'D000D': 'a',
        'D00UD': 'u',
        'D00DD': 'j',
        '0DU0D': 'i',
        '0DU0U': 'I',
        'D0UDD': 'b',
        'D0D0D': 'k',
        'D0DUD': 'y',
        'D0DDD': 'h',
        'DU00D': 'o',
        'DUD0D': 'n',
        '0DUDU': 'm',
        'DD00D': 'l',
        'UUUUD': '|',
        'UUUDD': '[',
        'UU0UD': ';',
        'UU00D': ',',
        'UUDDD': '/',
        'U0UUD': '!',
        'U0U0D': '#',
        'U0UDD': '?',
        'U00UD': ':',
        'UDUUD': '$',
        'UDDUD': ')',
        'UDDDD': '}',
        '0UUDD': '<',
        '0U0UD': '=',
        '0UDDD': '+',
        '0DUUD': '*',
        '0DUDD': '^',
        '0DDUD': '>',
        '0DD0D': '_',
        'DUUUD': '{',
        'DUUDD': '(',
        'DUDUD': '~',
        'DDUUD': '\\',
        'DDU0D': '.',
        'DDDUD': ']',
        'DDD0D': '&',
        'UUDDU': '%',
        '00UUU': '-',
        '00UDU': '`',
        '00DUU': '\'',
        '00DDU': '"',
        'D00UU': '@',
        'UU0DD': 'gr',
        'DU0DD': 'ow',
        'D0U0D': 'ng',
        'DDUDD': 'in',
        'DD0DD': 'nd',
        'DDDDD': 'ing',
        'UDDUU': 'thr',
        'DUUDU': 'the',
        'DU0UU': 'ou',
        'DUDUU': 'tr',
        'DUDDU': 'ch',
        'D00DU': 'ai',
        'D0DUU': 'th',
        'DDDUU': 'sh',
        'DDD0U': 'and',
        'UD0DD': 'for',
        'UDD0D': 'while',
        '0U0DD': 'if',
        '0UDUD': 'let',
        '0D0UD': 'let',
        '0D0DD': 'const',
        'UDU0D': 'not',
        'UD0UD': 'or',
    }

    generate_arduino_sketch(
        'ChordedKeyboard',
        default_schema,
        {
            'pinky_up_pin': 0,
            'pinky_down_pin': 0,
            'ring_up_pin': 0,
            'ring_down_pin': 0,
            'middle_up_pin': 0,
            'middle_down_pin': 0,
            'pointer_up_pin': 0,
            'pointer_down_pin': 0,
            'thumb_up_pin': 0,
            'thumb_down_pin': 0,
        }
    )
