"""
Run this script to generate an arduino sketch with a given
schema. We can't have arduino-time changeable schemas due to
the extremely small sketch and memory limits.

TODO: Add F-keys. Also modes.
"""

import os
import subprocess
from typing import Dict, List


class ChordedKeyboardSchema:
    def __init__(self, schema: Dict[str, str],
                 pins: Dict[str, int],
                 hold_down_keys: List[str]):
        self.schema = schema
        self.pins = pins
        self.hold_down_keys = hold_down_keys

    def generate_arduino_sketch(self, sketch_name: str) -> None:
        """
        Make an arduino sketch in the current directory with the
        given chorded keyboard schema.
        :param sketch_name: The arduino sketch's name. This will
            be a folder in the directory the script is run in.
        """
        fingers = [
            'pinky', 'ring', 'middle', 'pointer', 'thumb'
        ]

        required_pins = [
            f'{finger}_{state}_pin'
            for finger in fingers
            for state in ['up', 'down']
        ]
        assert len(self.pins) == 10, \
            'Wrong number of pin pairs provided'
        for pin in required_pins:
            assert pin in self.pins, f'Missing {pin}'

        # Create folder
        os.mkdir(sketch_name)

        # Create file
        fp = f'{sketch_name}/{sketch_name}.ino'
        with open(fp, 'w') as f:
            # Header stuff
            f.write(
                '// This file was generated by python\n'
                '#include <Keyboard.h>\n'
                'enum FingerState { UP, OFF, DOWN, BOTH };\n'
                'struct Chord { FingerState pinky = OFF, '
                'ring = OFF, middle = OFF, pointer = OFF, '
                'thumb = OFF; };\n'
                'enum Mode { NORMAL, NO_CONFIRM, F, WASD }'
                ' mode = NORMAL;\n'
            )

            # Pin information
            for pin in required_pins:
                p = self.pins[pin]
                f.write(f'const static int {pin} = {p};\n')

            # Setup
            f.write('void setup() {\n')
            for pin in required_pins:
                f.write(f'pinMode({pin}, INPUT_PULLUP);\n')

            # Turn off those red LEDs
            f.write('pinMode(LED_BUILTIN_TX, INPUT);\n')
            f.write('pinMode(LED_BUILTIN_RX, INPUT);\n')

            f.write('Keyboard.begin();\n}\n')

            # Loop
            f.write('bool holding = false;\n')
            f.write('bool post_compound = false;\n')
            f.write('void loop() {\nChord state;\n')
            for finger in fingers:
                f.write(
                    f'if (digitalRead({finger}_up_pin) == LOW) '
                    '{ state.' + finger + ' = UP; } if ('
                    f'digitalRead({finger}_down_pin) == LOW)'
                    ' { state.' + finger + f' = (state.{finger}'
                    ' == UP ? BOTH : DOWN); }\n'
                )

            # Normal mode
            f.write('if (mode == NORMAL) {')
            f.write(
                'if (state.thumb == OFF) { if (!holding) { '
                'Keyboard.releaseAll(); } '
                'if (post_compound) { '
                'post_compound = false; } return; }\n'
            )
            f.write('if (post_compound) { return; }\n')
            states = ['UP', 'OFF', 'BOTH', 'DOWN']
            for pinky in states:
                f.write(f'if (state.pinky == {pinky}) ' '{\n')
                for ring in states:
                    f.write(f'if (state.ring == {ring}) ' '{\n')
                    for middle in states:
                        f.write(f'if (state.middle == {middle})'
                                ' {\n')
                        for pointer in states:
                            f.write(
                                'if (state.pointer == '
                                f'{pointer}) ' '{\n'
                            )
                            for thumb in ['UP', 'BOTH', 'DOWN']:
                                f.write(
                                    'if (state.thumb == '
                                    f'{thumb}) ' '{\n'
                                )
                                chord = ''.join(
                                    [
                                        s[0]
                                        if s != 'OFF' else '0'
                                        for s in [
                                            pinky, ring, middle,
                                            pointer, thumb
                                        ]
                                    ]
                                )
                                if chord in self.schema:
                                    f.write(f'// {chord}\n')
                                    value = self.schema[chord]
                                    if len(value) == 1:
                                        # Single char
                                        f.write(
                                            'Keyboard.press(\''
                                            + (
                                                f'\\{value}'
                                                if value in [
                                                    '\'', '\\'
                                                ] else value
                                            ) + '\');\n'
                                            'holding = false;\n'
                                        )

                                    elif value.startswith(
                                            'MODE_'):
                                        # Mode switch
                                        f.write(
                                            'mode = '
                                            f'{value[5:]};\n'
                                        )

                                    elif value.startswith(
                                            'KEY_'):
                                        # Arduino keyboard
                                        # constant
                                        f.write(
                                            'Keyboard.press('
                                            f'{value});\n'
                                        )

                                        if value in \
                                                self\
                                                .hold_down_keys:
                                            f.write(
                                                'holding = '
                                                'true;'
                                            )

                                    else:
                                        # Compound chord
                                        f.write(
                                            'Keyboard.print("'
                                            f'{value}");\n'
                                            'holding = false;\n'
                                            'post_compound = '
                                            'true;\n'
                                        )

                                else:
                                    f.write(
                                        f'// {chord} is '
                                        'unused\n'
                                    )

                                f.write('}\n')
                                if thumb != 'DOWN':
                                    f.write(' else ')
                            f.write('}\n')
                            if pointer != 'DOWN':
                                f.write(' else ')
                        f.write('}\n')
                        if middle != 'DOWN':
                            f.write(' else ')
                    f.write('}\n')
                    if ring != 'DOWN':
                        f.write(' else ')
                f.write('}\n')
                if pinky != 'DOWN':
                    f.write(' else ')
            f.write('}\n')  # End normal mode

            f.write('else if (mode == WASD) {\n')
            f.write(
                'if (state.pointer == BOTH && '
                'state.middle == BOTH && '
                'state.ring == BOTH && '
                'state.pinky == BOTH) '
                '{ mode = NORMAL; return; }'
            )
            for finger, (bot, top) in [('pointer',
                                           ("'f'", "'r'")),
                                       ('middle',
                                           ("'d'", "'e'")),
                                       ('ring',
                                           ("'s'", "'w'")),
                                       ('pinky',
                                           ("'a'", "'q'")),
                                       ('thumb', (
                                           "' '",
                                           'KEY_LEFT_SHIFT'
                                        ))]:
                f.write(
                    f'switch (state.{finger}) '
                    '{case UP: '
                    f'Keyboard.press({top});'
                    f'Keyboard.release({bot});'
                    'break; case DOWN: '
                    f'Keyboard.press({bot});'
                    f'Keyboard.release({top});'
                    'break; case BOTH: '
                    f'Keyboard.press({bot});'
                    f'Keyboard.press({top});'
                    'break; case OFF: '
                    f'Keyboard.release({bot});'
                    f'Keyboard.release({top});'
                    'break;}'
                )
            f.write('}\n')  # End wasd mode

            # Invalid mode
            f.write('else { mode = NORMAL; }\n')
            f.write('}\n')

        # Attempt to format file
        subprocess.run(['clang-format', fp, '-i'], check=False)


# Begin part you should edit
arduino_project_name = 'ChordedKeyboard'
hold_down_keys = [
    'KEY_LEFT_CTRL',
    'KEY_LEFT_SHIFT',
    'KEY_LEFT_ALT',
    'KEY_LEFT_GUI',
    'KEY_RIGHT_CTRL',
    'KEY_RIGHT_SHIFT',
    'KEY_RIGHT_ALT',
    'KEY_RIGHT_GUI',
]
default_schema_dict = {
    'BBBBB': 'MODE_WASD',
    '0000U': 'KEY_TAB',
    '000DU': 'KEY_RIGHT_ARROW',
    '00D0U': 'KEY_UP_ARROW',
    '0D00U': 'KEY_DOWN_ARROW',
    '0DD0U': 'KEY_HOME',
    'UUUUU': 'KEY_ESC',
    'D000U': 'KEY_LEFT_ARROW',
    'DDDDU': 'KEY_CAPS_LOCK',
    '00UUD': 'KEY_RETURN',
    '0UU0D': 'KEY_BACKSPACE',
    'DU00U': 'KEY_LEFT_CTRL',
    'DD00U': 'KEY_LEFT_SHIFT',
    '0DU0U': 'KEY_LEFT_ALT',
    '0UDUU': 'KEY_LEFT_GUI',
    '000UU': '8',
    '00U0U': '4',
    '0U00U': '2',
    '0UU0U': '6',
    'U000U': '1',
    'U00UU': '9',
    'U0U0U': '5',
    'UU00U': '3',
    'UUU0U': '7',
    '0000D': ' ',
    '000UD': 'r',
    '000DD': 'f',
    '00U0D': 'e',
    '00UDD': 'v',
    '00D0D': 'd',
    '00DUD': 't',
    '00DDD': 'g',
    '0U00D': 'w',
    '0UUUD': '0',
    '0UD0D': 'c',
    '0D00D': 's',
    'U000D': 'q',
    'U00DD': 'p',
    'UD00D': 'x',
    'DUDDD': 'z',
    'D000D': 'a',
    'D00UD': 'u',
    'D00DD': 'j',
    '0DU0D': 'i',
    'D0UDD': 'b',
    'D0D0D': 'k',
    'D0DUD': 'y',
    'D0DDD': 'h',
    'DU00D': 'o',
    'DUD0D': 'n',
    '0DUDD': 'm',
    'DD00D': 'l',
    'UUUUD': '|',
    'UUUDD': '[',
    'UU0UD': ';',
    'UU00D': ',',
    'UUDDD': '/',
    'U0UUD': '!',
    'U0U0D': '#',
    'U0UDD': '?',
    'U00UD': ':',
    'UDUUD': '$',
    'UDDUD': ')',
    'UDDDD': '}',
    '0UUDD': '<',
    '0U0UD': '=',
    '0UDDD': '+',
    '0DUUD': '*',
    '0DUDU': '^',
    '0DDUD': '>',
    '0DD0D': '_',
    'DUUUD': '{',
    'DUUDD': '(',
    'DUDUD': '~',
    'DDUUD': '\\',
    'DDU0D': '.',
    'DDDUD': ']',
    'DDD0D': '&',
    'UUDDU': '%',
    '00UUU': '-',
    '00UDU': '`',
    '00DUU': '\'',
    '00DDU': '"',
    'D00UU': '@',
    'UU0DD': 'gr',
    'DU0DD': 'ow',
    'D0U0D': 'ng',
    'DDUDD': 'in',
    'DD0DD': 'nd',
    'DDDDD': 'ing',
    'UDDUU': 'thr',
    'DUUDU': 'the',
    'DU0UU': 'ou',
    'DUDUU': 'tr',
    'DUDDU': 'ch',
    'D00DU': 'ai',
    'D0DUU': 'th',
    'DDDUU': 'sh',
    'DDD0U': 'and',
    'UD0DD': 'for',
    'UDD0D': 'while',
    '0U0DD': 'if',
    '0UDUD': 'let',
    '0D0UD': 'let',
    '0D0DD': 'const',
    'UDU0D': 'not',
    'UD0UD': 'or',
    'U0DUD': 'qu',
}
pins = {
    'pinky_up_pin': 16,
    'pinky_down_pin': 10,
    'ring_up_pin': 15,
    'ring_down_pin': 14,
    'middle_up_pin': 3,
    'middle_down_pin': 4,
    'pointer_up_pin': 5,
    'pointer_down_pin': 6,
    'thumb_up_pin': 8,
    'thumb_down_pin': 9,
}
# End part you should edit

# The default schema as an object.
default_setup = ChordedKeyboardSchema(
    default_schema_dict, pins, hold_down_keys
)

if __name__ == '__main__':
    default_setup.generate_arduino_sketch(arduino_project_name)
