// This file was generated by a python script
#include <Keyboard.h>
enum FingerState { UP, OFF, DOWN };
struct Chord {
  FingerState pinky = OFF, ring = OFF, middle = OFF,
              pointer = OFF, thumb = OFF;
};
const static int pinky_up_pin = 16;
const static int pinky_down_pin = 10;
const static int ring_up_pin = 15;
const static int ring_down_pin = 14;
const static int middle_up_pin = 3;
const static int middle_down_pin = 4;
const static int pointer_up_pin = 5;
const static int pointer_down_pin = 6;
const static int thumb_up_pin = 8;
const static int thumb_down_pin = 9;
void setup() {
  pinMode(pinky_up_pin, INPUT_PULLUP);
  pinMode(pinky_down_pin, INPUT_PULLUP);
  pinMode(ring_up_pin, INPUT_PULLUP);
  pinMode(ring_down_pin, INPUT_PULLUP);
  pinMode(middle_up_pin, INPUT_PULLUP);
  pinMode(middle_down_pin, INPUT_PULLUP);
  pinMode(pointer_up_pin, INPUT_PULLUP);
  pinMode(pointer_down_pin, INPUT_PULLUP);
  pinMode(thumb_up_pin, INPUT_PULLUP);
  pinMode(thumb_down_pin, INPUT_PULLUP);
  pinMode(LED_BUILTIN_TX, INPUT);
  pinMode(LED_BUILTIN_RX, INPUT);
  Keyboard.begin();
}
void loop() {
  Chord state;
  if (digitalRead(pinky_up_pin) == LOW) {
    state.pinky = UP;
  } else if (digitalRead(pinky_down_pin) == LOW) {
    state.pinky = DOWN;
  }
  if (digitalRead(ring_up_pin) == LOW) {
    state.ring = UP;
  } else if (digitalRead(ring_down_pin) == LOW) {
    state.ring = DOWN;
  }
  if (digitalRead(middle_up_pin) == LOW) {
    state.middle = UP;
  } else if (digitalRead(middle_down_pin) == LOW) {
    state.middle = DOWN;
  }
  if (digitalRead(pointer_up_pin) == LOW) {
    state.pointer = UP;
  } else if (digitalRead(pointer_down_pin) == LOW) {
    state.pointer = DOWN;
  }
  if (digitalRead(thumb_up_pin) == LOW) {
    state.thumb = UP;
  } else if (digitalRead(thumb_down_pin) == LOW) {
    state.thumb = DOWN;
  } else {
    Keyboard.releaseAll();
    return;
  }
  if (state.pinky == UP) {
    if (state.ring == UP) {
      if (state.middle == UP) {
        if (state.pointer == UP) {
          if (state.thumb == UP) {
            Keyboard.press(KEY_ESC);
          } else if (state.thumb == DOWN) {
            Keyboard.press('|');
          }
        } else if (state.pointer == OFF) {
          if (state.thumb == UP) {
            Keyboard.press('7');
          } else if (state.thumb == DOWN) {
            // UUU0D is unused
            Keyboard.releaseAll();
          }
        } else if (state.pointer == DOWN) {
          if (state.thumb == UP) {
            // UUUDU is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.press('[');
          }
        }
      } else if (state.middle == OFF) {
        if (state.pointer == UP) {
          if (state.thumb == UP) {
            // UU0UU is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.press(';');
          }
        } else if (state.pointer == OFF) {
          if (state.thumb == UP) {
            Keyboard.press('3');
          } else if (state.thumb == DOWN) {
            Keyboard.press(',');
          }
        } else if (state.pointer == DOWN) {
          if (state.thumb == UP) {
            // UU0DU is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.print("gr");
            Keyboard.releaseAll();
          }
        }
      } else if (state.middle == DOWN) {
        if (state.pointer == UP) {
          if (state.thumb == UP) {
            // UUDUU is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            // UUDUD is unused
            Keyboard.releaseAll();
          }
        } else if (state.pointer == OFF) {
          if (state.thumb == UP) {
            // UUD0U is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            // UUD0D is unused
            Keyboard.releaseAll();
          }
        } else if (state.pointer == DOWN) {
          if (state.thumb == UP) {
            Keyboard.press('%');
          } else if (state.thumb == DOWN) {
            Keyboard.press('/');
          }
        }
      }
    } else if (state.ring == OFF) {
      if (state.middle == UP) {
        if (state.pointer == UP) {
          if (state.thumb == UP) {
            // U0UUU is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.press('!');
          }
        } else if (state.pointer == OFF) {
          if (state.thumb == UP) {
            Keyboard.press('5');
          } else if (state.thumb == DOWN) {
            Keyboard.press('#');
          }
        } else if (state.pointer == DOWN) {
          if (state.thumb == UP) {
            // U0UDU is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.press('?');
          }
        }
      } else if (state.middle == OFF) {
        if (state.pointer == UP) {
          if (state.thumb == UP) {
            Keyboard.press('9');
          } else if (state.thumb == DOWN) {
            Keyboard.press(':');
          }
        } else if (state.pointer == OFF) {
          if (state.thumb == UP) {
            Keyboard.press('1');
          } else if (state.thumb == DOWN) {
            Keyboard.press('q');
          }
        } else if (state.pointer == DOWN) {
          if (state.thumb == UP) {
            // U00DU is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.press('p');
          }
        }
      } else if (state.middle == DOWN) {
        if (state.pointer == UP) {
          if (state.thumb == UP) {
            // U0DUU is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            // U0DUD is unused
            Keyboard.releaseAll();
          }
        } else if (state.pointer == OFF) {
          if (state.thumb == UP) {
            // U0D0U is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            // U0D0D is unused
            Keyboard.releaseAll();
          }
        } else if (state.pointer == DOWN) {
          if (state.thumb == UP) {
            // U0DDU is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            // U0DDD is unused
            Keyboard.releaseAll();
          }
        }
      }
    } else if (state.ring == DOWN) {
      if (state.middle == UP) {
        if (state.pointer == UP) {
          if (state.thumb == UP) {
            // UDUUU is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.press('$');
          }
        } else if (state.pointer == OFF) {
          if (state.thumb == UP) {
            // UDU0U is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.print("not");
            Keyboard.releaseAll();
          }
        } else if (state.pointer == DOWN) {
          if (state.thumb == UP) {
            // UDUDU is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            // UDUDD is unused
            Keyboard.releaseAll();
          }
        }
      } else if (state.middle == OFF) {
        if (state.pointer == UP) {
          if (state.thumb == UP) {
            // UD0UU is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.print("or");
            Keyboard.releaseAll();
          }
        } else if (state.pointer == OFF) {
          if (state.thumb == UP) {
            // UD00U is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.press('x');
          }
        } else if (state.pointer == DOWN) {
          if (state.thumb == UP) {
            // UD0DU is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.print("for");
            Keyboard.releaseAll();
          }
        }
      } else if (state.middle == DOWN) {
        if (state.pointer == UP) {
          if (state.thumb == UP) {
            Keyboard.print("thr");
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.press(')');
          }
        } else if (state.pointer == OFF) {
          if (state.thumb == UP) {
            // UDD0U is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.print("while");
            Keyboard.releaseAll();
          }
        } else if (state.pointer == DOWN) {
          if (state.thumb == UP) {
            // UDDDU is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.press('}');
          }
        }
      }
    }
  } else if (state.pinky == OFF) {
    if (state.ring == UP) {
      if (state.middle == UP) {
        if (state.pointer == UP) {
          if (state.thumb == UP) {
            // 0UUUU is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.press('0');
          }
        } else if (state.pointer == OFF) {
          if (state.thumb == UP) {
            Keyboard.press('6');
          } else if (state.thumb == DOWN) {
            Keyboard.press(KEY_BACKSPACE);
          }
        } else if (state.pointer == DOWN) {
          if (state.thumb == UP) {
            // 0UUDU is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.press('<');
          }
        }
      } else if (state.middle == OFF) {
        if (state.pointer == UP) {
          if (state.thumb == UP) {
            // 0U0UU is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.press('=');
          }
        } else if (state.pointer == OFF) {
          if (state.thumb == UP) {
            Keyboard.press('2');
          } else if (state.thumb == DOWN) {
            Keyboard.press('w');
          }
        } else if (state.pointer == DOWN) {
          if (state.thumb == UP) {
            // 0U0DU is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.print("if");
            Keyboard.releaseAll();
          }
        }
      } else if (state.middle == DOWN) {
        if (state.pointer == UP) {
          if (state.thumb == UP) {
            // 0UDUU is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.print("let");
            Keyboard.releaseAll();
          }
        } else if (state.pointer == OFF) {
          if (state.thumb == UP) {
            // 0UD0U is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.press('c');
          }
        } else if (state.pointer == DOWN) {
          if (state.thumb == UP) {
            // 0UDDU is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.press('+');
          }
        }
      }
    } else if (state.ring == OFF) {
      if (state.middle == UP) {
        if (state.pointer == UP) {
          if (state.thumb == UP) {
            Keyboard.press('-');
          } else if (state.thumb == DOWN) {
            Keyboard.press(KEY_RETURN);
          }
        } else if (state.pointer == OFF) {
          if (state.thumb == UP) {
            Keyboard.press('4');
          } else if (state.thumb == DOWN) {
            Keyboard.press('e');
          }
        } else if (state.pointer == DOWN) {
          if (state.thumb == UP) {
            Keyboard.press('`');
          } else if (state.thumb == DOWN) {
            Keyboard.press('v');
          }
        }
      } else if (state.middle == OFF) {
        if (state.pointer == UP) {
          if (state.thumb == UP) {
            Keyboard.press('8');
          } else if (state.thumb == DOWN) {
            Keyboard.press('r');
          }
        } else if (state.pointer == OFF) {
          if (state.thumb == UP) {
            Keyboard.press(KEY_TAB);
          } else if (state.thumb == DOWN) {
            Keyboard.press(' ');
          }
        } else if (state.pointer == DOWN) {
          if (state.thumb == UP) {
            Keyboard.press(KEY_RIGHT_ARROW);
          } else if (state.thumb == DOWN) {
            Keyboard.press('f');
          }
        }
      } else if (state.middle == DOWN) {
        if (state.pointer == UP) {
          if (state.thumb == UP) {
            Keyboard.press('\'');
          } else if (state.thumb == DOWN) {
            Keyboard.press('t');
          }
        } else if (state.pointer == OFF) {
          if (state.thumb == UP) {
            Keyboard.press(KEY_UP_ARROW);
          } else if (state.thumb == DOWN) {
            Keyboard.press('d');
          }
        } else if (state.pointer == DOWN) {
          if (state.thumb == UP) {
            Keyboard.press('"');
          } else if (state.thumb == DOWN) {
            Keyboard.press('g');
          }
        }
      }
    } else if (state.ring == DOWN) {
      if (state.middle == UP) {
        if (state.pointer == UP) {
          if (state.thumb == UP) {
            // 0DUUU is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.press('*');
          }
        } else if (state.pointer == OFF) {
          if (state.thumb == UP) {
            Keyboard.press('I');
          } else if (state.thumb == DOWN) {
            Keyboard.press('i');
          }
        } else if (state.pointer == DOWN) {
          if (state.thumb == UP) {
            Keyboard.press('^');
          } else if (state.thumb == DOWN) {
            Keyboard.press('m');
          }
        }
      } else if (state.middle == OFF) {
        if (state.pointer == UP) {
          if (state.thumb == UP) {
            // 0D0UU is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.print("let");
            Keyboard.releaseAll();
          }
        } else if (state.pointer == OFF) {
          if (state.thumb == UP) {
            Keyboard.press(KEY_DOWN_ARROW);
          } else if (state.thumb == DOWN) {
            Keyboard.press('s');
          }
        } else if (state.pointer == DOWN) {
          if (state.thumb == UP) {
            // 0D0DU is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.print("const");
            Keyboard.releaseAll();
          }
        }
      } else if (state.middle == DOWN) {
        if (state.pointer == UP) {
          if (state.thumb == UP) {
            // 0DDUU is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.press('>');
          }
        } else if (state.pointer == OFF) {
          if (state.thumb == UP) {
            Keyboard.press(KEY_HOME);
          } else if (state.thumb == DOWN) {
            Keyboard.press('_');
          }
        } else if (state.pointer == DOWN) {
          if (state.thumb == UP) {
            // 0DDDU is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            // 0DDDD is unused
            Keyboard.releaseAll();
          }
        }
      }
    }
  } else if (state.pinky == DOWN) {
    if (state.ring == UP) {
      if (state.middle == UP) {
        if (state.pointer == UP) {
          if (state.thumb == UP) {
            // DUUUU is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.press('{');
          }
        } else if (state.pointer == OFF) {
          if (state.thumb == UP) {
            // DUU0U is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            // DUU0D is unused
            Keyboard.releaseAll();
          }
        } else if (state.pointer == DOWN) {
          if (state.thumb == UP) {
            Keyboard.print("the");
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.press('(');
          }
        }
      } else if (state.middle == OFF) {
        if (state.pointer == UP) {
          if (state.thumb == UP) {
            Keyboard.print("ou");
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            // DU0UD is unused
            Keyboard.releaseAll();
          }
        } else if (state.pointer == OFF) {
          if (state.thumb == UP) {
            // DU00U is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.press('o');
          }
        } else if (state.pointer == DOWN) {
          if (state.thumb == UP) {
            // DU0DU is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.print("ow");
            Keyboard.releaseAll();
          }
        }
      } else if (state.middle == DOWN) {
        if (state.pointer == UP) {
          if (state.thumb == UP) {
            Keyboard.print("tr");
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.press('~');
          }
        } else if (state.pointer == OFF) {
          if (state.thumb == UP) {
            // DUD0U is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.press('n');
          }
        } else if (state.pointer == DOWN) {
          if (state.thumb == UP) {
            Keyboard.print("ch");
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.press('z');
          }
        }
      }
    } else if (state.ring == OFF) {
      if (state.middle == UP) {
        if (state.pointer == UP) {
          if (state.thumb == UP) {
            // D0UUU is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            // D0UUD is unused
            Keyboard.releaseAll();
          }
        } else if (state.pointer == OFF) {
          if (state.thumb == UP) {
            // D0U0U is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.print("ng");
            Keyboard.releaseAll();
          }
        } else if (state.pointer == DOWN) {
          if (state.thumb == UP) {
            // D0UDU is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.press('b');
          }
        }
      } else if (state.middle == OFF) {
        if (state.pointer == UP) {
          if (state.thumb == UP) {
            Keyboard.press('@');
          } else if (state.thumb == DOWN) {
            Keyboard.press('u');
          }
        } else if (state.pointer == OFF) {
          if (state.thumb == UP) {
            Keyboard.press(KEY_LEFT_ARROW);
          } else if (state.thumb == DOWN) {
            Keyboard.press('a');
          }
        } else if (state.pointer == DOWN) {
          if (state.thumb == UP) {
            Keyboard.print("ai");
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.press('j');
          }
        }
      } else if (state.middle == DOWN) {
        if (state.pointer == UP) {
          if (state.thumb == UP) {
            Keyboard.print("th");
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.press('y');
          }
        } else if (state.pointer == OFF) {
          if (state.thumb == UP) {
            // D0D0U is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.press('k');
          }
        } else if (state.pointer == DOWN) {
          if (state.thumb == UP) {
            // D0DDU is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.press('h');
          }
        }
      }
    } else if (state.ring == DOWN) {
      if (state.middle == UP) {
        if (state.pointer == UP) {
          if (state.thumb == UP) {
            // DDUUU is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.press('\\');
          }
        } else if (state.pointer == OFF) {
          if (state.thumb == UP) {
            // DDU0U is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.press('.');
          }
        } else if (state.pointer == DOWN) {
          if (state.thumb == UP) {
            // DDUDU is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.print("in");
            Keyboard.releaseAll();
          }
        }
      } else if (state.middle == OFF) {
        if (state.pointer == UP) {
          if (state.thumb == UP) {
            // DD0UU is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            // DD0UD is unused
            Keyboard.releaseAll();
          }
        } else if (state.pointer == OFF) {
          if (state.thumb == UP) {
            // DD00U is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.press('l');
          }
        } else if (state.pointer == DOWN) {
          if (state.thumb == UP) {
            // DD0DU is unused
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.print("nd");
            Keyboard.releaseAll();
          }
        }
      } else if (state.middle == DOWN) {
        if (state.pointer == UP) {
          if (state.thumb == UP) {
            Keyboard.print("sh");
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.press(']');
          }
        } else if (state.pointer == OFF) {
          if (state.thumb == UP) {
            Keyboard.print("and");
            Keyboard.releaseAll();
          } else if (state.thumb == DOWN) {
            Keyboard.press('&');
          }
        } else if (state.pointer == DOWN) {
          if (state.thumb == UP) {
            Keyboard.press(KEY_CAPS_LOCK);
          } else if (state.thumb == DOWN) {
            Keyboard.print("ing");
            Keyboard.releaseAll();
          }
        }
      }
    }
  }
}
