// This file was generated by python
#include <Keyboard.h>
enum FingerState { UP, OFF, DOWN, BOTH };
struct Chord {
  FingerState pinky = OFF, ring = OFF, middle = OFF,
              pointer = OFF, thumb = OFF;
};
enum Mode { NORMAL, NO_CONFIRM, F, WASD } mode = NORMAL;
const static int pinky_up_pin = 16;
const static int pinky_down_pin = 10;
const static int ring_up_pin = 15;
const static int ring_down_pin = 14;
const static int middle_up_pin = 3;
const static int middle_down_pin = 4;
const static int pointer_up_pin = 5;
const static int pointer_down_pin = 6;
const static int thumb_up_pin = 8;
const static int thumb_down_pin = 9;
void setup() {
  pinMode(pinky_up_pin, INPUT_PULLUP);
  pinMode(pinky_down_pin, INPUT_PULLUP);
  pinMode(ring_up_pin, INPUT_PULLUP);
  pinMode(ring_down_pin, INPUT_PULLUP);
  pinMode(middle_up_pin, INPUT_PULLUP);
  pinMode(middle_down_pin, INPUT_PULLUP);
  pinMode(pointer_up_pin, INPUT_PULLUP);
  pinMode(pointer_down_pin, INPUT_PULLUP);
  pinMode(thumb_up_pin, INPUT_PULLUP);
  pinMode(thumb_down_pin, INPUT_PULLUP);
  pinMode(LED_BUILTIN_TX, INPUT);
  pinMode(LED_BUILTIN_RX, INPUT);
  Keyboard.begin();
}
bool holding = false;
bool post_compound = false;
void loop() {
  Chord state;
  if (digitalRead(pinky_up_pin) == LOW) {
    state.pinky = UP;
  }
  if (digitalRead(pinky_down_pin) == LOW) {
    state.pinky = (state.pinky == UP ? BOTH : DOWN);
  }
  if (digitalRead(ring_up_pin) == LOW) {
    state.ring = UP;
  }
  if (digitalRead(ring_down_pin) == LOW) {
    state.ring = (state.ring == UP ? BOTH : DOWN);
  }
  if (digitalRead(middle_up_pin) == LOW) {
    state.middle = UP;
  }
  if (digitalRead(middle_down_pin) == LOW) {
    state.middle = (state.middle == UP ? BOTH : DOWN);
  }
  if (digitalRead(pointer_up_pin) == LOW) {
    state.pointer = UP;
  }
  if (digitalRead(pointer_down_pin) == LOW) {
    state.pointer = (state.pointer == UP ? BOTH : DOWN);
  }
  if (digitalRead(thumb_up_pin) == LOW) {
    state.thumb = UP;
  }
  if (digitalRead(thumb_down_pin) == LOW) {
    state.thumb = (state.thumb == UP ? BOTH : DOWN);
  }
  if (mode == NORMAL) {
    if (state.thumb == OFF) {
      if (!holding) {
        Keyboard.releaseAll();
      }
      if (post_compound) {
        post_compound = false;
      }
      return;
    }
    if (post_compound) {
      return;
    }
    if (state.pinky == UP) {
      if (state.ring == UP) {
        if (state.middle == UP) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // UUUUU
              Keyboard.press(KEY_ESC);
            } else if (state.thumb == BOTH) {
              // UUUUB is unused
            } else if (state.thumb == DOWN) {
              // UUUUD
              Keyboard.press('|');
              holding = false;
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // UUU0U
              Keyboard.press('7');
              holding = false;
            } else if (state.thumb == BOTH) {
              // UUU0B is unused
            } else if (state.thumb == DOWN) {
              // UUU0D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // UUUBU is unused
            } else if (state.thumb == BOTH) {
              // UUUBB is unused
            } else if (state.thumb == DOWN) {
              // UUUBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // UUUDU is unused
            } else if (state.thumb == BOTH) {
              // UUUDB is unused
            } else if (state.thumb == DOWN) {
              // UUUDD
              Keyboard.press('[');
              holding = false;
            }
          }
        } else if (state.middle == OFF) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // UU0UU is unused
            } else if (state.thumb == BOTH) {
              // UU0UB is unused
            } else if (state.thumb == DOWN) {
              // UU0UD
              Keyboard.press(';');
              holding = false;
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // UU00U
              Keyboard.press('3');
              holding = false;
            } else if (state.thumb == BOTH) {
              // UU00B is unused
            } else if (state.thumb == DOWN) {
              // UU00D
              Keyboard.press(',');
              holding = false;
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // UU0BU is unused
            } else if (state.thumb == BOTH) {
              // UU0BB is unused
            } else if (state.thumb == DOWN) {
              // UU0BD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // UU0DU is unused
            } else if (state.thumb == BOTH) {
              // UU0DB is unused
            } else if (state.thumb == DOWN) {
              // UU0DD
              Keyboard.print("gr");
              holding = false;
              post_compound = true;
            }
          }
        } else if (state.middle == BOTH) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // UUBUU is unused
            } else if (state.thumb == BOTH) {
              // UUBUB is unused
            } else if (state.thumb == DOWN) {
              // UUBUD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // UUB0U is unused
            } else if (state.thumb == BOTH) {
              // UUB0B is unused
            } else if (state.thumb == DOWN) {
              // UUB0D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // UUBBU is unused
            } else if (state.thumb == BOTH) {
              // UUBBB is unused
            } else if (state.thumb == DOWN) {
              // UUBBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // UUBDU is unused
            } else if (state.thumb == BOTH) {
              // UUBDB is unused
            } else if (state.thumb == DOWN) {
              // UUBDD is unused
            }
          }
        } else if (state.middle == DOWN) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // UUDUU is unused
            } else if (state.thumb == BOTH) {
              // UUDUB is unused
            } else if (state.thumb == DOWN) {
              // UUDUD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // UUD0U is unused
            } else if (state.thumb == BOTH) {
              // UUD0B is unused
            } else if (state.thumb == DOWN) {
              // UUD0D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // UUDBU is unused
            } else if (state.thumb == BOTH) {
              // UUDBB is unused
            } else if (state.thumb == DOWN) {
              // UUDBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // UUDDU
              Keyboard.press('%');
              holding = false;
            } else if (state.thumb == BOTH) {
              // UUDDB is unused
            } else if (state.thumb == DOWN) {
              // UUDDD
              Keyboard.press('/');
              holding = false;
            }
          }
        }
      } else if (state.ring == OFF) {
        if (state.middle == UP) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // U0UUU is unused
            } else if (state.thumb == BOTH) {
              // U0UUB is unused
            } else if (state.thumb == DOWN) {
              // U0UUD
              Keyboard.press('!');
              holding = false;
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // U0U0U
              Keyboard.press('5');
              holding = false;
            } else if (state.thumb == BOTH) {
              // U0U0B is unused
            } else if (state.thumb == DOWN) {
              // U0U0D
              Keyboard.press('#');
              holding = false;
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // U0UBU is unused
            } else if (state.thumb == BOTH) {
              // U0UBB is unused
            } else if (state.thumb == DOWN) {
              // U0UBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // U0UDU is unused
            } else if (state.thumb == BOTH) {
              // U0UDB is unused
            } else if (state.thumb == DOWN) {
              // U0UDD
              Keyboard.press('?');
              holding = false;
            }
          }
        } else if (state.middle == OFF) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // U00UU
              Keyboard.press('9');
              holding = false;
            } else if (state.thumb == BOTH) {
              // U00UB is unused
            } else if (state.thumb == DOWN) {
              // U00UD
              Keyboard.press(':');
              holding = false;
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // U000U
              Keyboard.press('1');
              holding = false;
            } else if (state.thumb == BOTH) {
              // U000B is unused
            } else if (state.thumb == DOWN) {
              // U000D
              Keyboard.press('q');
              holding = false;
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // U00BU is unused
            } else if (state.thumb == BOTH) {
              // U00BB is unused
            } else if (state.thumb == DOWN) {
              // U00BD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // U00DU is unused
            } else if (state.thumb == BOTH) {
              // U00DB is unused
            } else if (state.thumb == DOWN) {
              // U00DD
              Keyboard.press('p');
              holding = false;
            }
          }
        } else if (state.middle == BOTH) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // U0BUU is unused
            } else if (state.thumb == BOTH) {
              // U0BUB is unused
            } else if (state.thumb == DOWN) {
              // U0BUD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // U0B0U is unused
            } else if (state.thumb == BOTH) {
              // U0B0B is unused
            } else if (state.thumb == DOWN) {
              // U0B0D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // U0BBU is unused
            } else if (state.thumb == BOTH) {
              // U0BBB is unused
            } else if (state.thumb == DOWN) {
              // U0BBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // U0BDU is unused
            } else if (state.thumb == BOTH) {
              // U0BDB is unused
            } else if (state.thumb == DOWN) {
              // U0BDD is unused
            }
          }
        } else if (state.middle == DOWN) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // U0DUU is unused
            } else if (state.thumb == BOTH) {
              // U0DUB is unused
            } else if (state.thumb == DOWN) {
              // U0DUD
              Keyboard.print("qu");
              holding = false;
              post_compound = true;
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // U0D0U is unused
            } else if (state.thumb == BOTH) {
              // U0D0B is unused
            } else if (state.thumb == DOWN) {
              // U0D0D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // U0DBU is unused
            } else if (state.thumb == BOTH) {
              // U0DBB is unused
            } else if (state.thumb == DOWN) {
              // U0DBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // U0DDU is unused
            } else if (state.thumb == BOTH) {
              // U0DDB is unused
            } else if (state.thumb == DOWN) {
              // U0DDD is unused
            }
          }
        }
      } else if (state.ring == BOTH) {
        if (state.middle == UP) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // UBUUU is unused
            } else if (state.thumb == BOTH) {
              // UBUUB is unused
            } else if (state.thumb == DOWN) {
              // UBUUD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // UBU0U is unused
            } else if (state.thumb == BOTH) {
              // UBU0B is unused
            } else if (state.thumb == DOWN) {
              // UBU0D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // UBUBU is unused
            } else if (state.thumb == BOTH) {
              // UBUBB is unused
            } else if (state.thumb == DOWN) {
              // UBUBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // UBUDU is unused
            } else if (state.thumb == BOTH) {
              // UBUDB is unused
            } else if (state.thumb == DOWN) {
              // UBUDD is unused
            }
          }
        } else if (state.middle == OFF) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // UB0UU is unused
            } else if (state.thumb == BOTH) {
              // UB0UB is unused
            } else if (state.thumb == DOWN) {
              // UB0UD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // UB00U is unused
            } else if (state.thumb == BOTH) {
              // UB00B is unused
            } else if (state.thumb == DOWN) {
              // UB00D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // UB0BU is unused
            } else if (state.thumb == BOTH) {
              // UB0BB is unused
            } else if (state.thumb == DOWN) {
              // UB0BD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // UB0DU is unused
            } else if (state.thumb == BOTH) {
              // UB0DB is unused
            } else if (state.thumb == DOWN) {
              // UB0DD is unused
            }
          }
        } else if (state.middle == BOTH) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // UBBUU is unused
            } else if (state.thumb == BOTH) {
              // UBBUB is unused
            } else if (state.thumb == DOWN) {
              // UBBUD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // UBB0U is unused
            } else if (state.thumb == BOTH) {
              // UBB0B is unused
            } else if (state.thumb == DOWN) {
              // UBB0D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // UBBBU is unused
            } else if (state.thumb == BOTH) {
              // UBBBB is unused
            } else if (state.thumb == DOWN) {
              // UBBBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // UBBDU is unused
            } else if (state.thumb == BOTH) {
              // UBBDB is unused
            } else if (state.thumb == DOWN) {
              // UBBDD is unused
            }
          }
        } else if (state.middle == DOWN) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // UBDUU is unused
            } else if (state.thumb == BOTH) {
              // UBDUB is unused
            } else if (state.thumb == DOWN) {
              // UBDUD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // UBD0U is unused
            } else if (state.thumb == BOTH) {
              // UBD0B is unused
            } else if (state.thumb == DOWN) {
              // UBD0D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // UBDBU is unused
            } else if (state.thumb == BOTH) {
              // UBDBB is unused
            } else if (state.thumb == DOWN) {
              // UBDBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // UBDDU is unused
            } else if (state.thumb == BOTH) {
              // UBDDB is unused
            } else if (state.thumb == DOWN) {
              // UBDDD is unused
            }
          }
        }
      } else if (state.ring == DOWN) {
        if (state.middle == UP) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // UDUUU is unused
            } else if (state.thumb == BOTH) {
              // UDUUB is unused
            } else if (state.thumb == DOWN) {
              // UDUUD
              Keyboard.press('$');
              holding = false;
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // UDU0U is unused
            } else if (state.thumb == BOTH) {
              // UDU0B is unused
            } else if (state.thumb == DOWN) {
              // UDU0D
              Keyboard.print("not");
              holding = false;
              post_compound = true;
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // UDUBU is unused
            } else if (state.thumb == BOTH) {
              // UDUBB is unused
            } else if (state.thumb == DOWN) {
              // UDUBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // UDUDU is unused
            } else if (state.thumb == BOTH) {
              // UDUDB is unused
            } else if (state.thumb == DOWN) {
              // UDUDD is unused
            }
          }
        } else if (state.middle == OFF) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // UD0UU is unused
            } else if (state.thumb == BOTH) {
              // UD0UB is unused
            } else if (state.thumb == DOWN) {
              // UD0UD
              Keyboard.print("or");
              holding = false;
              post_compound = true;
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // UD00U is unused
            } else if (state.thumb == BOTH) {
              // UD00B is unused
            } else if (state.thumb == DOWN) {
              // UD00D
              Keyboard.press('x');
              holding = false;
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // UD0BU is unused
            } else if (state.thumb == BOTH) {
              // UD0BB is unused
            } else if (state.thumb == DOWN) {
              // UD0BD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // UD0DU is unused
            } else if (state.thumb == BOTH) {
              // UD0DB is unused
            } else if (state.thumb == DOWN) {
              // UD0DD
              Keyboard.print("for");
              holding = false;
              post_compound = true;
            }
          }
        } else if (state.middle == BOTH) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // UDBUU is unused
            } else if (state.thumb == BOTH) {
              // UDBUB is unused
            } else if (state.thumb == DOWN) {
              // UDBUD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // UDB0U is unused
            } else if (state.thumb == BOTH) {
              // UDB0B is unused
            } else if (state.thumb == DOWN) {
              // UDB0D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // UDBBU is unused
            } else if (state.thumb == BOTH) {
              // UDBBB is unused
            } else if (state.thumb == DOWN) {
              // UDBBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // UDBDU is unused
            } else if (state.thumb == BOTH) {
              // UDBDB is unused
            } else if (state.thumb == DOWN) {
              // UDBDD is unused
            }
          }
        } else if (state.middle == DOWN) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // UDDUU
              Keyboard.print("thr");
              holding = false;
              post_compound = true;
            } else if (state.thumb == BOTH) {
              // UDDUB is unused
            } else if (state.thumb == DOWN) {
              // UDDUD
              Keyboard.press(')');
              holding = false;
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // UDD0U is unused
            } else if (state.thumb == BOTH) {
              // UDD0B is unused
            } else if (state.thumb == DOWN) {
              // UDD0D
              Keyboard.print("while");
              holding = false;
              post_compound = true;
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // UDDBU is unused
            } else if (state.thumb == BOTH) {
              // UDDBB is unused
            } else if (state.thumb == DOWN) {
              // UDDBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // UDDDU is unused
            } else if (state.thumb == BOTH) {
              // UDDDB is unused
            } else if (state.thumb == DOWN) {
              // UDDDD
              Keyboard.press('}');
              holding = false;
            }
          }
        }
      }
    } else if (state.pinky == OFF) {
      if (state.ring == UP) {
        if (state.middle == UP) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // 0UUUU is unused
            } else if (state.thumb == BOTH) {
              // 0UUUB is unused
            } else if (state.thumb == DOWN) {
              // 0UUUD
              Keyboard.press('0');
              holding = false;
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // 0UU0U
              Keyboard.press('6');
              holding = false;
            } else if (state.thumb == BOTH) {
              // 0UU0B is unused
            } else if (state.thumb == DOWN) {
              // 0UU0D
              Keyboard.press(KEY_BACKSPACE);
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // 0UUBU is unused
            } else if (state.thumb == BOTH) {
              // 0UUBB is unused
            } else if (state.thumb == DOWN) {
              // 0UUBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // 0UUDU is unused
            } else if (state.thumb == BOTH) {
              // 0UUDB is unused
            } else if (state.thumb == DOWN) {
              // 0UUDD
              Keyboard.press('<');
              holding = false;
            }
          }
        } else if (state.middle == OFF) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // 0U0UU is unused
            } else if (state.thumb == BOTH) {
              // 0U0UB is unused
            } else if (state.thumb == DOWN) {
              // 0U0UD
              Keyboard.press('=');
              holding = false;
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // 0U00U
              Keyboard.press('2');
              holding = false;
            } else if (state.thumb == BOTH) {
              // 0U00B is unused
            } else if (state.thumb == DOWN) {
              // 0U00D
              Keyboard.press('w');
              holding = false;
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // 0U0BU is unused
            } else if (state.thumb == BOTH) {
              // 0U0BB is unused
            } else if (state.thumb == DOWN) {
              // 0U0BD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // 0U0DU is unused
            } else if (state.thumb == BOTH) {
              // 0U0DB is unused
            } else if (state.thumb == DOWN) {
              // 0U0DD
              Keyboard.print("if");
              holding = false;
              post_compound = true;
            }
          }
        } else if (state.middle == BOTH) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // 0UBUU is unused
            } else if (state.thumb == BOTH) {
              // 0UBUB is unused
            } else if (state.thumb == DOWN) {
              // 0UBUD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // 0UB0U is unused
            } else if (state.thumb == BOTH) {
              // 0UB0B is unused
            } else if (state.thumb == DOWN) {
              // 0UB0D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // 0UBBU is unused
            } else if (state.thumb == BOTH) {
              // 0UBBB is unused
            } else if (state.thumb == DOWN) {
              // 0UBBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // 0UBDU is unused
            } else if (state.thumb == BOTH) {
              // 0UBDB is unused
            } else if (state.thumb == DOWN) {
              // 0UBDD is unused
            }
          }
        } else if (state.middle == DOWN) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // 0UDUU
              Keyboard.press(KEY_LEFT_GUI);
              holding = true;
            } else if (state.thumb == BOTH) {
              // 0UDUB is unused
            } else if (state.thumb == DOWN) {
              // 0UDUD
              Keyboard.print("let");
              holding = false;
              post_compound = true;
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // 0UD0U is unused
            } else if (state.thumb == BOTH) {
              // 0UD0B is unused
            } else if (state.thumb == DOWN) {
              // 0UD0D
              Keyboard.press('c');
              holding = false;
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // 0UDBU is unused
            } else if (state.thumb == BOTH) {
              // 0UDBB is unused
            } else if (state.thumb == DOWN) {
              // 0UDBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // 0UDDU is unused
            } else if (state.thumb == BOTH) {
              // 0UDDB is unused
            } else if (state.thumb == DOWN) {
              // 0UDDD
              Keyboard.press('+');
              holding = false;
            }
          }
        }
      } else if (state.ring == OFF) {
        if (state.middle == UP) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // 00UUU
              Keyboard.press('-');
              holding = false;
            } else if (state.thumb == BOTH) {
              // 00UUB is unused
            } else if (state.thumb == DOWN) {
              // 00UUD
              Keyboard.press(KEY_RETURN);
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // 00U0U
              Keyboard.press('4');
              holding = false;
            } else if (state.thumb == BOTH) {
              // 00U0B is unused
            } else if (state.thumb == DOWN) {
              // 00U0D
              Keyboard.press('e');
              holding = false;
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // 00UBU is unused
            } else if (state.thumb == BOTH) {
              // 00UBB is unused
            } else if (state.thumb == DOWN) {
              // 00UBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // 00UDU
              Keyboard.press('`');
              holding = false;
            } else if (state.thumb == BOTH) {
              // 00UDB is unused
            } else if (state.thumb == DOWN) {
              // 00UDD
              Keyboard.press('v');
              holding = false;
            }
          }
        } else if (state.middle == OFF) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // 000UU
              Keyboard.press('8');
              holding = false;
            } else if (state.thumb == BOTH) {
              // 000UB is unused
            } else if (state.thumb == DOWN) {
              // 000UD
              Keyboard.press('r');
              holding = false;
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // 0000U
              Keyboard.press(KEY_TAB);
            } else if (state.thumb == BOTH) {
              // 0000B is unused
            } else if (state.thumb == DOWN) {
              // 0000D
              Keyboard.press(' ');
              holding = false;
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // 000BU is unused
            } else if (state.thumb == BOTH) {
              // 000BB is unused
            } else if (state.thumb == DOWN) {
              // 000BD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // 000DU
              Keyboard.press(KEY_RIGHT_ARROW);
            } else if (state.thumb == BOTH) {
              // 000DB is unused
            } else if (state.thumb == DOWN) {
              // 000DD
              Keyboard.press('f');
              holding = false;
            }
          }
        } else if (state.middle == BOTH) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // 00BUU is unused
            } else if (state.thumb == BOTH) {
              // 00BUB is unused
            } else if (state.thumb == DOWN) {
              // 00BUD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // 00B0U is unused
            } else if (state.thumb == BOTH) {
              // 00B0B is unused
            } else if (state.thumb == DOWN) {
              // 00B0D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // 00BBU is unused
            } else if (state.thumb == BOTH) {
              // 00BBB is unused
            } else if (state.thumb == DOWN) {
              // 00BBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // 00BDU is unused
            } else if (state.thumb == BOTH) {
              // 00BDB is unused
            } else if (state.thumb == DOWN) {
              // 00BDD is unused
            }
          }
        } else if (state.middle == DOWN) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // 00DUU
              Keyboard.press('\'');
              holding = false;
            } else if (state.thumb == BOTH) {
              // 00DUB is unused
            } else if (state.thumb == DOWN) {
              // 00DUD
              Keyboard.press('t');
              holding = false;
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // 00D0U
              Keyboard.press(KEY_UP_ARROW);
            } else if (state.thumb == BOTH) {
              // 00D0B is unused
            } else if (state.thumb == DOWN) {
              // 00D0D
              Keyboard.press('d');
              holding = false;
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // 00DBU is unused
            } else if (state.thumb == BOTH) {
              // 00DBB is unused
            } else if (state.thumb == DOWN) {
              // 00DBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // 00DDU
              Keyboard.press('"');
              holding = false;
            } else if (state.thumb == BOTH) {
              // 00DDB is unused
            } else if (state.thumb == DOWN) {
              // 00DDD
              Keyboard.press('g');
              holding = false;
            }
          }
        }
      } else if (state.ring == BOTH) {
        if (state.middle == UP) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // 0BUUU is unused
            } else if (state.thumb == BOTH) {
              // 0BUUB is unused
            } else if (state.thumb == DOWN) {
              // 0BUUD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // 0BU0U is unused
            } else if (state.thumb == BOTH) {
              // 0BU0B is unused
            } else if (state.thumb == DOWN) {
              // 0BU0D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // 0BUBU is unused
            } else if (state.thumb == BOTH) {
              // 0BUBB is unused
            } else if (state.thumb == DOWN) {
              // 0BUBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // 0BUDU is unused
            } else if (state.thumb == BOTH) {
              // 0BUDB is unused
            } else if (state.thumb == DOWN) {
              // 0BUDD is unused
            }
          }
        } else if (state.middle == OFF) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // 0B0UU is unused
            } else if (state.thumb == BOTH) {
              // 0B0UB is unused
            } else if (state.thumb == DOWN) {
              // 0B0UD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // 0B00U is unused
            } else if (state.thumb == BOTH) {
              // 0B00B is unused
            } else if (state.thumb == DOWN) {
              // 0B00D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // 0B0BU is unused
            } else if (state.thumb == BOTH) {
              // 0B0BB is unused
            } else if (state.thumb == DOWN) {
              // 0B0BD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // 0B0DU is unused
            } else if (state.thumb == BOTH) {
              // 0B0DB is unused
            } else if (state.thumb == DOWN) {
              // 0B0DD is unused
            }
          }
        } else if (state.middle == BOTH) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // 0BBUU is unused
            } else if (state.thumb == BOTH) {
              // 0BBUB is unused
            } else if (state.thumb == DOWN) {
              // 0BBUD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // 0BB0U is unused
            } else if (state.thumb == BOTH) {
              // 0BB0B is unused
            } else if (state.thumb == DOWN) {
              // 0BB0D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // 0BBBU is unused
            } else if (state.thumb == BOTH) {
              // 0BBBB is unused
            } else if (state.thumb == DOWN) {
              // 0BBBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // 0BBDU is unused
            } else if (state.thumb == BOTH) {
              // 0BBDB is unused
            } else if (state.thumb == DOWN) {
              // 0BBDD is unused
            }
          }
        } else if (state.middle == DOWN) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // 0BDUU is unused
            } else if (state.thumb == BOTH) {
              // 0BDUB is unused
            } else if (state.thumb == DOWN) {
              // 0BDUD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // 0BD0U is unused
            } else if (state.thumb == BOTH) {
              // 0BD0B is unused
            } else if (state.thumb == DOWN) {
              // 0BD0D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // 0BDBU is unused
            } else if (state.thumb == BOTH) {
              // 0BDBB is unused
            } else if (state.thumb == DOWN) {
              // 0BDBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // 0BDDU is unused
            } else if (state.thumb == BOTH) {
              // 0BDDB is unused
            } else if (state.thumb == DOWN) {
              // 0BDDD is unused
            }
          }
        }
      } else if (state.ring == DOWN) {
        if (state.middle == UP) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // 0DUUU is unused
            } else if (state.thumb == BOTH) {
              // 0DUUB is unused
            } else if (state.thumb == DOWN) {
              // 0DUUD
              Keyboard.press('*');
              holding = false;
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // 0DU0U
              Keyboard.press(KEY_LEFT_ALT);
              holding = true;
            } else if (state.thumb == BOTH) {
              // 0DU0B is unused
            } else if (state.thumb == DOWN) {
              // 0DU0D
              Keyboard.press('i');
              holding = false;
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // 0DUBU is unused
            } else if (state.thumb == BOTH) {
              // 0DUBB is unused
            } else if (state.thumb == DOWN) {
              // 0DUBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // 0DUDU
              Keyboard.press('^');
              holding = false;
            } else if (state.thumb == BOTH) {
              // 0DUDB is unused
            } else if (state.thumb == DOWN) {
              // 0DUDD
              Keyboard.press('m');
              holding = false;
            }
          }
        } else if (state.middle == OFF) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // 0D0UU is unused
            } else if (state.thumb == BOTH) {
              // 0D0UB is unused
            } else if (state.thumb == DOWN) {
              // 0D0UD
              Keyboard.print("let");
              holding = false;
              post_compound = true;
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // 0D00U
              Keyboard.press(KEY_DOWN_ARROW);
            } else if (state.thumb == BOTH) {
              // 0D00B is unused
            } else if (state.thumb == DOWN) {
              // 0D00D
              Keyboard.press('s');
              holding = false;
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // 0D0BU is unused
            } else if (state.thumb == BOTH) {
              // 0D0BB is unused
            } else if (state.thumb == DOWN) {
              // 0D0BD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // 0D0DU is unused
            } else if (state.thumb == BOTH) {
              // 0D0DB is unused
            } else if (state.thumb == DOWN) {
              // 0D0DD
              Keyboard.print("const");
              holding = false;
              post_compound = true;
            }
          }
        } else if (state.middle == BOTH) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // 0DBUU is unused
            } else if (state.thumb == BOTH) {
              // 0DBUB is unused
            } else if (state.thumb == DOWN) {
              // 0DBUD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // 0DB0U is unused
            } else if (state.thumb == BOTH) {
              // 0DB0B is unused
            } else if (state.thumb == DOWN) {
              // 0DB0D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // 0DBBU is unused
            } else if (state.thumb == BOTH) {
              // 0DBBB is unused
            } else if (state.thumb == DOWN) {
              // 0DBBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // 0DBDU is unused
            } else if (state.thumb == BOTH) {
              // 0DBDB is unused
            } else if (state.thumb == DOWN) {
              // 0DBDD is unused
            }
          }
        } else if (state.middle == DOWN) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // 0DDUU is unused
            } else if (state.thumb == BOTH) {
              // 0DDUB is unused
            } else if (state.thumb == DOWN) {
              // 0DDUD
              Keyboard.press('>');
              holding = false;
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // 0DD0U
              Keyboard.press(KEY_HOME);
            } else if (state.thumb == BOTH) {
              // 0DD0B is unused
            } else if (state.thumb == DOWN) {
              // 0DD0D
              Keyboard.press('_');
              holding = false;
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // 0DDBU is unused
            } else if (state.thumb == BOTH) {
              // 0DDBB is unused
            } else if (state.thumb == DOWN) {
              // 0DDBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // 0DDDU is unused
            } else if (state.thumb == BOTH) {
              // 0DDDB is unused
            } else if (state.thumb == DOWN) {
              // 0DDDD is unused
            }
          }
        }
      }
    } else if (state.pinky == BOTH) {
      if (state.ring == UP) {
        if (state.middle == UP) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // BUUUU is unused
            } else if (state.thumb == BOTH) {
              // BUUUB is unused
            } else if (state.thumb == DOWN) {
              // BUUUD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // BUU0U is unused
            } else if (state.thumb == BOTH) {
              // BUU0B is unused
            } else if (state.thumb == DOWN) {
              // BUU0D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // BUUBU is unused
            } else if (state.thumb == BOTH) {
              // BUUBB is unused
            } else if (state.thumb == DOWN) {
              // BUUBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // BUUDU is unused
            } else if (state.thumb == BOTH) {
              // BUUDB is unused
            } else if (state.thumb == DOWN) {
              // BUUDD is unused
            }
          }
        } else if (state.middle == OFF) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // BU0UU is unused
            } else if (state.thumb == BOTH) {
              // BU0UB is unused
            } else if (state.thumb == DOWN) {
              // BU0UD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // BU00U is unused
            } else if (state.thumb == BOTH) {
              // BU00B is unused
            } else if (state.thumb == DOWN) {
              // BU00D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // BU0BU is unused
            } else if (state.thumb == BOTH) {
              // BU0BB is unused
            } else if (state.thumb == DOWN) {
              // BU0BD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // BU0DU is unused
            } else if (state.thumb == BOTH) {
              // BU0DB is unused
            } else if (state.thumb == DOWN) {
              // BU0DD is unused
            }
          }
        } else if (state.middle == BOTH) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // BUBUU is unused
            } else if (state.thumb == BOTH) {
              // BUBUB is unused
            } else if (state.thumb == DOWN) {
              // BUBUD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // BUB0U is unused
            } else if (state.thumb == BOTH) {
              // BUB0B is unused
            } else if (state.thumb == DOWN) {
              // BUB0D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // BUBBU is unused
            } else if (state.thumb == BOTH) {
              // BUBBB is unused
            } else if (state.thumb == DOWN) {
              // BUBBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // BUBDU is unused
            } else if (state.thumb == BOTH) {
              // BUBDB is unused
            } else if (state.thumb == DOWN) {
              // BUBDD is unused
            }
          }
        } else if (state.middle == DOWN) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // BUDUU is unused
            } else if (state.thumb == BOTH) {
              // BUDUB is unused
            } else if (state.thumb == DOWN) {
              // BUDUD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // BUD0U is unused
            } else if (state.thumb == BOTH) {
              // BUD0B is unused
            } else if (state.thumb == DOWN) {
              // BUD0D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // BUDBU is unused
            } else if (state.thumb == BOTH) {
              // BUDBB is unused
            } else if (state.thumb == DOWN) {
              // BUDBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // BUDDU is unused
            } else if (state.thumb == BOTH) {
              // BUDDB is unused
            } else if (state.thumb == DOWN) {
              // BUDDD is unused
            }
          }
        }
      } else if (state.ring == OFF) {
        if (state.middle == UP) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // B0UUU is unused
            } else if (state.thumb == BOTH) {
              // B0UUB is unused
            } else if (state.thumb == DOWN) {
              // B0UUD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // B0U0U is unused
            } else if (state.thumb == BOTH) {
              // B0U0B is unused
            } else if (state.thumb == DOWN) {
              // B0U0D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // B0UBU is unused
            } else if (state.thumb == BOTH) {
              // B0UBB is unused
            } else if (state.thumb == DOWN) {
              // B0UBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // B0UDU is unused
            } else if (state.thumb == BOTH) {
              // B0UDB is unused
            } else if (state.thumb == DOWN) {
              // B0UDD is unused
            }
          }
        } else if (state.middle == OFF) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // B00UU is unused
            } else if (state.thumb == BOTH) {
              // B00UB is unused
            } else if (state.thumb == DOWN) {
              // B00UD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // B000U is unused
            } else if (state.thumb == BOTH) {
              // B000B is unused
            } else if (state.thumb == DOWN) {
              // B000D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // B00BU is unused
            } else if (state.thumb == BOTH) {
              // B00BB is unused
            } else if (state.thumb == DOWN) {
              // B00BD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // B00DU is unused
            } else if (state.thumb == BOTH) {
              // B00DB is unused
            } else if (state.thumb == DOWN) {
              // B00DD is unused
            }
          }
        } else if (state.middle == BOTH) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // B0BUU is unused
            } else if (state.thumb == BOTH) {
              // B0BUB is unused
            } else if (state.thumb == DOWN) {
              // B0BUD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // B0B0U is unused
            } else if (state.thumb == BOTH) {
              // B0B0B is unused
            } else if (state.thumb == DOWN) {
              // B0B0D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // B0BBU is unused
            } else if (state.thumb == BOTH) {
              // B0BBB is unused
            } else if (state.thumb == DOWN) {
              // B0BBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // B0BDU is unused
            } else if (state.thumb == BOTH) {
              // B0BDB is unused
            } else if (state.thumb == DOWN) {
              // B0BDD is unused
            }
          }
        } else if (state.middle == DOWN) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // B0DUU is unused
            } else if (state.thumb == BOTH) {
              // B0DUB is unused
            } else if (state.thumb == DOWN) {
              // B0DUD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // B0D0U is unused
            } else if (state.thumb == BOTH) {
              // B0D0B is unused
            } else if (state.thumb == DOWN) {
              // B0D0D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // B0DBU is unused
            } else if (state.thumb == BOTH) {
              // B0DBB is unused
            } else if (state.thumb == DOWN) {
              // B0DBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // B0DDU is unused
            } else if (state.thumb == BOTH) {
              // B0DDB is unused
            } else if (state.thumb == DOWN) {
              // B0DDD is unused
            }
          }
        }
      } else if (state.ring == BOTH) {
        if (state.middle == UP) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // BBUUU is unused
            } else if (state.thumb == BOTH) {
              // BBUUB is unused
            } else if (state.thumb == DOWN) {
              // BBUUD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // BBU0U is unused
            } else if (state.thumb == BOTH) {
              // BBU0B is unused
            } else if (state.thumb == DOWN) {
              // BBU0D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // BBUBU is unused
            } else if (state.thumb == BOTH) {
              // BBUBB is unused
            } else if (state.thumb == DOWN) {
              // BBUBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // BBUDU is unused
            } else if (state.thumb == BOTH) {
              // BBUDB is unused
            } else if (state.thumb == DOWN) {
              // BBUDD is unused
            }
          }
        } else if (state.middle == OFF) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // BB0UU is unused
            } else if (state.thumb == BOTH) {
              // BB0UB is unused
            } else if (state.thumb == DOWN) {
              // BB0UD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // BB00U is unused
            } else if (state.thumb == BOTH) {
              // BB00B is unused
            } else if (state.thumb == DOWN) {
              // BB00D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // BB0BU is unused
            } else if (state.thumb == BOTH) {
              // BB0BB is unused
            } else if (state.thumb == DOWN) {
              // BB0BD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // BB0DU is unused
            } else if (state.thumb == BOTH) {
              // BB0DB is unused
            } else if (state.thumb == DOWN) {
              // BB0DD is unused
            }
          }
        } else if (state.middle == BOTH) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // BBBUU is unused
            } else if (state.thumb == BOTH) {
              // BBBUB is unused
            } else if (state.thumb == DOWN) {
              // BBBUD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // BBB0U is unused
            } else if (state.thumb == BOTH) {
              // BBB0B is unused
            } else if (state.thumb == DOWN) {
              // BBB0D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // BBBBU is unused
            } else if (state.thumb == BOTH) {
              // BBBBB
              mode = WASD;
            } else if (state.thumb == DOWN) {
              // BBBBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // BBBDU is unused
            } else if (state.thumb == BOTH) {
              // BBBDB is unused
            } else if (state.thumb == DOWN) {
              // BBBDD is unused
            }
          }
        } else if (state.middle == DOWN) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // BBDUU is unused
            } else if (state.thumb == BOTH) {
              // BBDUB is unused
            } else if (state.thumb == DOWN) {
              // BBDUD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // BBD0U is unused
            } else if (state.thumb == BOTH) {
              // BBD0B is unused
            } else if (state.thumb == DOWN) {
              // BBD0D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // BBDBU is unused
            } else if (state.thumb == BOTH) {
              // BBDBB is unused
            } else if (state.thumb == DOWN) {
              // BBDBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // BBDDU is unused
            } else if (state.thumb == BOTH) {
              // BBDDB is unused
            } else if (state.thumb == DOWN) {
              // BBDDD is unused
            }
          }
        }
      } else if (state.ring == DOWN) {
        if (state.middle == UP) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // BDUUU is unused
            } else if (state.thumb == BOTH) {
              // BDUUB is unused
            } else if (state.thumb == DOWN) {
              // BDUUD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // BDU0U is unused
            } else if (state.thumb == BOTH) {
              // BDU0B is unused
            } else if (state.thumb == DOWN) {
              // BDU0D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // BDUBU is unused
            } else if (state.thumb == BOTH) {
              // BDUBB is unused
            } else if (state.thumb == DOWN) {
              // BDUBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // BDUDU is unused
            } else if (state.thumb == BOTH) {
              // BDUDB is unused
            } else if (state.thumb == DOWN) {
              // BDUDD is unused
            }
          }
        } else if (state.middle == OFF) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // BD0UU is unused
            } else if (state.thumb == BOTH) {
              // BD0UB is unused
            } else if (state.thumb == DOWN) {
              // BD0UD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // BD00U is unused
            } else if (state.thumb == BOTH) {
              // BD00B is unused
            } else if (state.thumb == DOWN) {
              // BD00D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // BD0BU is unused
            } else if (state.thumb == BOTH) {
              // BD0BB is unused
            } else if (state.thumb == DOWN) {
              // BD0BD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // BD0DU is unused
            } else if (state.thumb == BOTH) {
              // BD0DB is unused
            } else if (state.thumb == DOWN) {
              // BD0DD is unused
            }
          }
        } else if (state.middle == BOTH) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // BDBUU is unused
            } else if (state.thumb == BOTH) {
              // BDBUB is unused
            } else if (state.thumb == DOWN) {
              // BDBUD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // BDB0U is unused
            } else if (state.thumb == BOTH) {
              // BDB0B is unused
            } else if (state.thumb == DOWN) {
              // BDB0D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // BDBBU is unused
            } else if (state.thumb == BOTH) {
              // BDBBB is unused
            } else if (state.thumb == DOWN) {
              // BDBBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // BDBDU is unused
            } else if (state.thumb == BOTH) {
              // BDBDB is unused
            } else if (state.thumb == DOWN) {
              // BDBDD is unused
            }
          }
        } else if (state.middle == DOWN) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // BDDUU is unused
            } else if (state.thumb == BOTH) {
              // BDDUB is unused
            } else if (state.thumb == DOWN) {
              // BDDUD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // BDD0U is unused
            } else if (state.thumb == BOTH) {
              // BDD0B is unused
            } else if (state.thumb == DOWN) {
              // BDD0D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // BDDBU is unused
            } else if (state.thumb == BOTH) {
              // BDDBB is unused
            } else if (state.thumb == DOWN) {
              // BDDBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // BDDDU is unused
            } else if (state.thumb == BOTH) {
              // BDDDB is unused
            } else if (state.thumb == DOWN) {
              // BDDDD is unused
            }
          }
        }
      }
    } else if (state.pinky == DOWN) {
      if (state.ring == UP) {
        if (state.middle == UP) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // DUUUU is unused
            } else if (state.thumb == BOTH) {
              // DUUUB is unused
            } else if (state.thumb == DOWN) {
              // DUUUD
              Keyboard.press('{');
              holding = false;
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // DUU0U is unused
            } else if (state.thumb == BOTH) {
              // DUU0B is unused
            } else if (state.thumb == DOWN) {
              // DUU0D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // DUUBU is unused
            } else if (state.thumb == BOTH) {
              // DUUBB is unused
            } else if (state.thumb == DOWN) {
              // DUUBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // DUUDU
              Keyboard.print("the");
              holding = false;
              post_compound = true;
            } else if (state.thumb == BOTH) {
              // DUUDB is unused
            } else if (state.thumb == DOWN) {
              // DUUDD
              Keyboard.press('(');
              holding = false;
            }
          }
        } else if (state.middle == OFF) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // DU0UU
              Keyboard.print("ou");
              holding = false;
              post_compound = true;
            } else if (state.thumb == BOTH) {
              // DU0UB is unused
            } else if (state.thumb == DOWN) {
              // DU0UD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // DU00U
              Keyboard.press(KEY_LEFT_CTRL);
              holding = true;
            } else if (state.thumb == BOTH) {
              // DU00B is unused
            } else if (state.thumb == DOWN) {
              // DU00D
              Keyboard.press('o');
              holding = false;
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // DU0BU is unused
            } else if (state.thumb == BOTH) {
              // DU0BB is unused
            } else if (state.thumb == DOWN) {
              // DU0BD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // DU0DU is unused
            } else if (state.thumb == BOTH) {
              // DU0DB is unused
            } else if (state.thumb == DOWN) {
              // DU0DD
              Keyboard.print("ow");
              holding = false;
              post_compound = true;
            }
          }
        } else if (state.middle == BOTH) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // DUBUU is unused
            } else if (state.thumb == BOTH) {
              // DUBUB is unused
            } else if (state.thumb == DOWN) {
              // DUBUD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // DUB0U is unused
            } else if (state.thumb == BOTH) {
              // DUB0B is unused
            } else if (state.thumb == DOWN) {
              // DUB0D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // DUBBU is unused
            } else if (state.thumb == BOTH) {
              // DUBBB is unused
            } else if (state.thumb == DOWN) {
              // DUBBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // DUBDU is unused
            } else if (state.thumb == BOTH) {
              // DUBDB is unused
            } else if (state.thumb == DOWN) {
              // DUBDD is unused
            }
          }
        } else if (state.middle == DOWN) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // DUDUU
              Keyboard.print("tr");
              holding = false;
              post_compound = true;
            } else if (state.thumb == BOTH) {
              // DUDUB is unused
            } else if (state.thumb == DOWN) {
              // DUDUD
              Keyboard.press('~');
              holding = false;
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // DUD0U is unused
            } else if (state.thumb == BOTH) {
              // DUD0B is unused
            } else if (state.thumb == DOWN) {
              // DUD0D
              Keyboard.press('n');
              holding = false;
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // DUDBU is unused
            } else if (state.thumb == BOTH) {
              // DUDBB is unused
            } else if (state.thumb == DOWN) {
              // DUDBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // DUDDU
              Keyboard.print("ch");
              holding = false;
              post_compound = true;
            } else if (state.thumb == BOTH) {
              // DUDDB is unused
            } else if (state.thumb == DOWN) {
              // DUDDD
              Keyboard.press('z');
              holding = false;
            }
          }
        }
      } else if (state.ring == OFF) {
        if (state.middle == UP) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // D0UUU is unused
            } else if (state.thumb == BOTH) {
              // D0UUB is unused
            } else if (state.thumb == DOWN) {
              // D0UUD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // D0U0U is unused
            } else if (state.thumb == BOTH) {
              // D0U0B is unused
            } else if (state.thumb == DOWN) {
              // D0U0D
              Keyboard.print("ng");
              holding = false;
              post_compound = true;
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // D0UBU is unused
            } else if (state.thumb == BOTH) {
              // D0UBB is unused
            } else if (state.thumb == DOWN) {
              // D0UBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // D0UDU is unused
            } else if (state.thumb == BOTH) {
              // D0UDB is unused
            } else if (state.thumb == DOWN) {
              // D0UDD
              Keyboard.press('b');
              holding = false;
            }
          }
        } else if (state.middle == OFF) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // D00UU
              Keyboard.press('@');
              holding = false;
            } else if (state.thumb == BOTH) {
              // D00UB is unused
            } else if (state.thumb == DOWN) {
              // D00UD
              Keyboard.press('u');
              holding = false;
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // D000U
              Keyboard.press(KEY_LEFT_ARROW);
            } else if (state.thumb == BOTH) {
              // D000B is unused
            } else if (state.thumb == DOWN) {
              // D000D
              Keyboard.press('a');
              holding = false;
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // D00BU is unused
            } else if (state.thumb == BOTH) {
              // D00BB is unused
            } else if (state.thumb == DOWN) {
              // D00BD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // D00DU
              Keyboard.print("ai");
              holding = false;
              post_compound = true;
            } else if (state.thumb == BOTH) {
              // D00DB is unused
            } else if (state.thumb == DOWN) {
              // D00DD
              Keyboard.press('j');
              holding = false;
            }
          }
        } else if (state.middle == BOTH) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // D0BUU is unused
            } else if (state.thumb == BOTH) {
              // D0BUB is unused
            } else if (state.thumb == DOWN) {
              // D0BUD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // D0B0U is unused
            } else if (state.thumb == BOTH) {
              // D0B0B is unused
            } else if (state.thumb == DOWN) {
              // D0B0D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // D0BBU is unused
            } else if (state.thumb == BOTH) {
              // D0BBB is unused
            } else if (state.thumb == DOWN) {
              // D0BBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // D0BDU is unused
            } else if (state.thumb == BOTH) {
              // D0BDB is unused
            } else if (state.thumb == DOWN) {
              // D0BDD is unused
            }
          }
        } else if (state.middle == DOWN) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // D0DUU
              Keyboard.print("th");
              holding = false;
              post_compound = true;
            } else if (state.thumb == BOTH) {
              // D0DUB is unused
            } else if (state.thumb == DOWN) {
              // D0DUD
              Keyboard.press('y');
              holding = false;
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // D0D0U is unused
            } else if (state.thumb == BOTH) {
              // D0D0B is unused
            } else if (state.thumb == DOWN) {
              // D0D0D
              Keyboard.press('k');
              holding = false;
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // D0DBU is unused
            } else if (state.thumb == BOTH) {
              // D0DBB is unused
            } else if (state.thumb == DOWN) {
              // D0DBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // D0DDU is unused
            } else if (state.thumb == BOTH) {
              // D0DDB is unused
            } else if (state.thumb == DOWN) {
              // D0DDD
              Keyboard.press('h');
              holding = false;
            }
          }
        }
      } else if (state.ring == BOTH) {
        if (state.middle == UP) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // DBUUU is unused
            } else if (state.thumb == BOTH) {
              // DBUUB is unused
            } else if (state.thumb == DOWN) {
              // DBUUD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // DBU0U is unused
            } else if (state.thumb == BOTH) {
              // DBU0B is unused
            } else if (state.thumb == DOWN) {
              // DBU0D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // DBUBU is unused
            } else if (state.thumb == BOTH) {
              // DBUBB is unused
            } else if (state.thumb == DOWN) {
              // DBUBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // DBUDU is unused
            } else if (state.thumb == BOTH) {
              // DBUDB is unused
            } else if (state.thumb == DOWN) {
              // DBUDD is unused
            }
          }
        } else if (state.middle == OFF) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // DB0UU is unused
            } else if (state.thumb == BOTH) {
              // DB0UB is unused
            } else if (state.thumb == DOWN) {
              // DB0UD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // DB00U is unused
            } else if (state.thumb == BOTH) {
              // DB00B is unused
            } else if (state.thumb == DOWN) {
              // DB00D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // DB0BU is unused
            } else if (state.thumb == BOTH) {
              // DB0BB is unused
            } else if (state.thumb == DOWN) {
              // DB0BD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // DB0DU is unused
            } else if (state.thumb == BOTH) {
              // DB0DB is unused
            } else if (state.thumb == DOWN) {
              // DB0DD is unused
            }
          }
        } else if (state.middle == BOTH) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // DBBUU is unused
            } else if (state.thumb == BOTH) {
              // DBBUB is unused
            } else if (state.thumb == DOWN) {
              // DBBUD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // DBB0U is unused
            } else if (state.thumb == BOTH) {
              // DBB0B is unused
            } else if (state.thumb == DOWN) {
              // DBB0D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // DBBBU is unused
            } else if (state.thumb == BOTH) {
              // DBBBB is unused
            } else if (state.thumb == DOWN) {
              // DBBBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // DBBDU is unused
            } else if (state.thumb == BOTH) {
              // DBBDB is unused
            } else if (state.thumb == DOWN) {
              // DBBDD is unused
            }
          }
        } else if (state.middle == DOWN) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // DBDUU is unused
            } else if (state.thumb == BOTH) {
              // DBDUB is unused
            } else if (state.thumb == DOWN) {
              // DBDUD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // DBD0U is unused
            } else if (state.thumb == BOTH) {
              // DBD0B is unused
            } else if (state.thumb == DOWN) {
              // DBD0D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // DBDBU is unused
            } else if (state.thumb == BOTH) {
              // DBDBB is unused
            } else if (state.thumb == DOWN) {
              // DBDBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // DBDDU is unused
            } else if (state.thumb == BOTH) {
              // DBDDB is unused
            } else if (state.thumb == DOWN) {
              // DBDDD is unused
            }
          }
        }
      } else if (state.ring == DOWN) {
        if (state.middle == UP) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // DDUUU is unused
            } else if (state.thumb == BOTH) {
              // DDUUB is unused
            } else if (state.thumb == DOWN) {
              // DDUUD
              Keyboard.press('\\');
              holding = false;
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // DDU0U is unused
            } else if (state.thumb == BOTH) {
              // DDU0B is unused
            } else if (state.thumb == DOWN) {
              // DDU0D
              Keyboard.press('.');
              holding = false;
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // DDUBU is unused
            } else if (state.thumb == BOTH) {
              // DDUBB is unused
            } else if (state.thumb == DOWN) {
              // DDUBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // DDUDU is unused
            } else if (state.thumb == BOTH) {
              // DDUDB is unused
            } else if (state.thumb == DOWN) {
              // DDUDD
              Keyboard.print("in");
              holding = false;
              post_compound = true;
            }
          }
        } else if (state.middle == OFF) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // DD0UU is unused
            } else if (state.thumb == BOTH) {
              // DD0UB is unused
            } else if (state.thumb == DOWN) {
              // DD0UD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // DD00U
              Keyboard.press(KEY_LEFT_SHIFT);
              holding = true;
            } else if (state.thumb == BOTH) {
              // DD00B is unused
            } else if (state.thumb == DOWN) {
              // DD00D
              Keyboard.press('l');
              holding = false;
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // DD0BU is unused
            } else if (state.thumb == BOTH) {
              // DD0BB is unused
            } else if (state.thumb == DOWN) {
              // DD0BD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // DD0DU is unused
            } else if (state.thumb == BOTH) {
              // DD0DB is unused
            } else if (state.thumb == DOWN) {
              // DD0DD
              Keyboard.print("nd");
              holding = false;
              post_compound = true;
            }
          }
        } else if (state.middle == BOTH) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // DDBUU is unused
            } else if (state.thumb == BOTH) {
              // DDBUB is unused
            } else if (state.thumb == DOWN) {
              // DDBUD is unused
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // DDB0U is unused
            } else if (state.thumb == BOTH) {
              // DDB0B is unused
            } else if (state.thumb == DOWN) {
              // DDB0D is unused
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // DDBBU is unused
            } else if (state.thumb == BOTH) {
              // DDBBB is unused
            } else if (state.thumb == DOWN) {
              // DDBBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // DDBDU is unused
            } else if (state.thumb == BOTH) {
              // DDBDB is unused
            } else if (state.thumb == DOWN) {
              // DDBDD is unused
            }
          }
        } else if (state.middle == DOWN) {
          if (state.pointer == UP) {
            if (state.thumb == UP) {
              // DDDUU
              Keyboard.print("sh");
              holding = false;
              post_compound = true;
            } else if (state.thumb == BOTH) {
              // DDDUB is unused
            } else if (state.thumb == DOWN) {
              // DDDUD
              Keyboard.press(']');
              holding = false;
            }
          } else if (state.pointer == OFF) {
            if (state.thumb == UP) {
              // DDD0U
              Keyboard.print("and");
              holding = false;
              post_compound = true;
            } else if (state.thumb == BOTH) {
              // DDD0B is unused
            } else if (state.thumb == DOWN) {
              // DDD0D
              Keyboard.press('&');
              holding = false;
            }
          } else if (state.pointer == BOTH) {
            if (state.thumb == UP) {
              // DDDBU is unused
            } else if (state.thumb == BOTH) {
              // DDDBB is unused
            } else if (state.thumb == DOWN) {
              // DDDBD is unused
            }
          } else if (state.pointer == DOWN) {
            if (state.thumb == UP) {
              // DDDDU
              Keyboard.press(KEY_CAPS_LOCK);
            } else if (state.thumb == BOTH) {
              // DDDDB is unused
            } else if (state.thumb == DOWN) {
              // DDDDD
              Keyboard.print("ing");
              holding = false;
              post_compound = true;
            }
          }
        }
      }
    }
  } else if (mode == WASD) {
    if (state.pointer == BOTH && state.middle == BOTH &&
        state.ring == BOTH && state.pinky == BOTH) {
      mode = NORMAL;
      return;
    }
    switch (state.pointer) {
    case UP:
      Keyboard.press('r');
      Keyboard.release('f');
      break;
    case DOWN:
      Keyboard.press('f');
      Keyboard.release('r');
      break;
    case BOTH:
      Keyboard.press('f');
      Keyboard.press('r');
      break;
    case OFF:
      Keyboard.release('f');
      Keyboard.release('r');
      break;
    }
    switch (state.middle) {
    case UP:
      Keyboard.press('e');
      Keyboard.release('d');
      break;
    case DOWN:
      Keyboard.press('d');
      Keyboard.release('e');
      break;
    case BOTH:
      Keyboard.press('d');
      Keyboard.press('e');
      break;
    case OFF:
      Keyboard.release('d');
      Keyboard.release('e');
      break;
    }
    switch (state.ring) {
    case UP:
      Keyboard.press('w');
      Keyboard.release('s');
      break;
    case DOWN:
      Keyboard.press('s');
      Keyboard.release('w');
      break;
    case BOTH:
      Keyboard.press('s');
      Keyboard.press('w');
      break;
    case OFF:
      Keyboard.release('s');
      Keyboard.release('w');
      break;
    }
    switch (state.pinky) {
    case UP:
      Keyboard.press('q');
      Keyboard.release('a');
      break;
    case DOWN:
      Keyboard.press('a');
      Keyboard.release('q');
      break;
    case BOTH:
      Keyboard.press('a');
      Keyboard.press('q');
      break;
    case OFF:
      Keyboard.release('a');
      Keyboard.release('q');
      break;
    }
    switch (state.thumb) {
    case UP:
      Keyboard.press(KEY_LEFT_SHIFT);
      Keyboard.release(' ');
      break;
    case DOWN:
      Keyboard.press(' ');
      Keyboard.release(KEY_LEFT_SHIFT);
      break;
    case BOTH:
      Keyboard.press(' ');
      Keyboard.press(KEY_LEFT_SHIFT);
      break;
    case OFF:
      Keyboard.release(' ');
      Keyboard.release(KEY_LEFT_SHIFT);
      break;
    }
  } else {
    mode = NORMAL;
  }
}
